{
 "title": "Bandwidth",
 "time": { "from": "now+4h-15m", "to": "now+4h" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "MinQueryTime", "query": "1970-01-01 00:00:00" },
   { "name": "MaxQueryTime", "query": "YYYY-MM-DD hh:mm:ss" },
   { "name": "QuerySize", "query": "100,1000,10000" }
  ]
 },
 "panels": [
  {
   "title": "StoreStandardOperations Calls (Origin)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT txhash, txtime, amount, explorerlink FROM (SELECT txhash, txtime, amount, explorerlink FROM storestandardoperations WHERE (origin = true AND txtime >= '${MinQueryTime:raw}' AND txtime <= '${MaxQueryTime:raw}') ORDER BY txtime DESC LIMIT '${QuerySize:raw}') temp ORDER BY txtime ASC"
    }
   ]
  },
  {
   "title": "StoreStandardOperations Calls (Destination)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT txhash, txtime, amount, explorerlink FROM (SELECT txhash, txtime, amount, explorerlink FROM storestandardoperations WHERE (origin = false AND txtime >= '${MinQueryTime:raw}' AND txtime <= '${MaxQueryTime:raw}') ORDER BY txtime DESC LIMIT '${QuerySize:raw}') temp ORDER BY txtime ASC"
    }
   ]
  },
  {
   "title": "ExecuteStandardOperations Calls (Destination)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT txhash, txtime, partialamount, explorerlink FROM (SELECT txhash, txtime, partialamount, explorerlink FROM executestandardoperations WHERE (origin = false AND txtime >= '${MinQueryTime:raw}' AND txtime <= '${MaxQueryTime:raw}') ORDER BY txtime DESC LIMIT '${QuerySize:raw}') temp ORDER BY txtime ASC"
    }
   ]
  },
  {
   "title": "ExecuteStandardOperations Calls (Origin)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT txhash, txtime, partialamount, explorerlink FROM (SELECT txhash, txtime, partialamount, explorerlink FROM executestandardoperations WHERE (origin = true AND txtime >= '${MinQueryTime:raw}' AND txtime <= '${MaxQueryTime:raw}') ORDER BY txtime DESC LIMIT '${QuerySize:raw}') temp ORDER BY txtime ASC"
    }
   ]
  },
  {
   "title": "Bandwidth Used Ratio (Destination)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT currentusedbandwidth, currenttotalbandwidth FROM bandwidthproviders WHERE origin = false LIMIT 50 "
    }
   ]
  },
  {
   "title": "Origin and Destination Bandwidth Share",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT origin, currenttotalbandwidth FROM bandwidthproviders LIMIT 50 "
    }
   ]
  },
  {
   "title": "Bandwidth Used Ratio (Origin)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT currentusedbandwidth, currenttotalbandwidth FROM bandwidthproviders WHERE origin = true LIMIT 50 "
    }
   ]
  }
 ]
}